name: Claude Code (Reusable)

on:
  workflow_call:
    inputs:
      trigger_phrase:
        description: 'Phrase that triggers Claude (e.g., /jd, /claude)'
        required: false
        type: string
        default: '/jd'
      branch_prefix:
        description: 'Prefix for branches created by Claude'
        required: false
        type: string
        default: 'jd/'
      assignee_trigger:
        description: 'Assignee name that triggers Claude (e.g., @bot-name)'
        required: false
        type: string
        default: ''
      label_trigger:
        description: 'Label that triggers Claude'
        required: false
        type: string
        default: 'jd'
      plugin_marketplaces:
        description: 'Plugin marketplace repositories (comma-separated)'
        required: false
        type: string
        default: ''
      plugins:
        description: 'Plugins to load (comma-separated)'
        required: false
        type: string
        default: ''
      claude_args:
        description: 'Additional arguments to pass to Claude'
        required: false
        type: string
        default: ''
      use_commit_signing:
        description: 'Enable commit signing'
        required: false
        type: boolean
        default: false
      custom_prompt:
        description: 'Optional custom prompt for Claude'
        required: false
        type: string
        default: ''
    secrets:
      BOT_ID:
        description: 'GitHub App ID for custom bot'
        required: true
      BOT_KEY:
        description: 'GitHub App private key for custom bot'
        required: true
      CLAUDE_CODE_OAUTH_TOKEN:
        description: 'OAuth token for Claude Code'
        required: true

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Initialize custom bot
        id: bot
        uses: starburst997/custom-bot-init@v1
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ steps.bot.outputs.token }}
          bot_id: ${{ secrets.BOT_ID }}
          bot_name: ${{ steps.bot.outputs.name }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          allowed_bots: ${{ steps.bot.outputs.slug }}
          plugin_marketplaces: ${{ inputs.plugin_marketplaces }}
          plugins: ${{ inputs.plugins }}
          trigger_phrase: ${{ inputs.trigger_phrase }}
          branch_prefix: ${{ inputs.branch_prefix }}
          assignee_trigger: ${{ inputs.assignee_trigger != '' && inputs.assignee_trigger || format('@{0}', steps.bot.outputs.slug) }}
          label_trigger: ${{ inputs.label_trigger }}
          use_commit_signing: ${{ inputs.use_commit_signing }}
          prompt: ${{ inputs.custom_prompt }}
          claude_args: ${{ inputs.claude_args }}
