name: Claude Code Review (Reusable)

on:
  workflow_call:
    inputs:
      trigger_phrase:
        description: 'Phrase that triggers Claude (e.g., /jd, /claude)'
        required: false
        type: string
        default: '/jd'
      branch_prefix:
        description: 'Prefix for branches created by Claude'
        required: false
        type: string
        default: 'jd/'
      assignee_trigger:
        description: 'Assignee name that triggers Claude (e.g., @bot-name)'
        required: false
        type: string
        default: ''
      label_trigger:
        description: 'Label that triggers Claude'
        required: false
        type: string
        default: 'jd'
      plugin_marketplaces:
        description: 'Plugin marketplace repositories (comma-separated)'
        required: false
        type: string
        default: ''
      plugins:
        description: 'Plugins to load (comma-separated)'
        required: false
        type: string
        default: ''
      claude_args:
        description: 'Additional arguments to pass to Claude'
        required: false
        type: string
        default: ''
      use_commit_signing:
        description: 'Enable commit signing'
        required: false
        type: boolean
        default: false
      review_prompt:
        description: 'Custom prompt for code review'
        required: false
        type: string
        default: ''
      paths_filter:
        description: 'Comma-separated list of file patterns to review (e.g., src/**/*.ts,src/**/*.js)'
        required: false
        type: string
        default: ''
      author_filter:
        description: 'Only review PRs from specific authors (comma-separated usernames)'
        required: false
        type: string
        default: ''
    secrets:
      BOT_ID:
        description: 'GitHub App ID for custom bot'
        required: true
      BOT_KEY:
        description: 'GitHub App private key for custom bot'
        required: true
      CLAUDE_CODE_OAUTH_TOKEN:
        description: 'OAuth token for Claude Code'
        required: true

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Initialize custom bot
        id: bot
        uses: starburst997/custom-bot-init@v1
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          prompt: ${{ inputs.review_prompt != '' && inputs.review_prompt || format('REPO: {0}\nPR NUMBER: {1}\n\nPlease review this pull request and provide feedback on:\n- Code quality and best practices\n- Potential bugs or issues\n- Performance considerations\n- Security concerns\n- Test coverage\n\nUse the repository''s CLAUDE.md for guidance on style and conventions. Be constructive and helpful in your feedback.\n\nUse `gh pr comment` with your Bash tool to leave your review as a comment on the PR.', github.repository, github.event.pull_request.number) }}
          claude_args: ${{ inputs.claude_args }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ steps.bot.outputs.token }}
          bot_id: ${{ secrets.BOT_ID }}
          bot_name: ${{ steps.bot.outputs.name }}
          allowed_bots: ${{ steps.bot.outputs.slug }}
          plugin_marketplaces: ${{ inputs.plugin_marketplaces }}
          plugins: ${{ inputs.plugins }}
          trigger_phrase: ${{ inputs.trigger_phrase }}
          branch_prefix: ${{ inputs.branch_prefix }}
          assignee_trigger: ${{ inputs.assignee_trigger != '' && inputs.assignee_trigger || format('@{0}', steps.bot.outputs.slug) }}
          label_trigger: ${{ inputs.label_trigger }}
          use_commit_signing: ${{ inputs.use_commit_signing }}
