name: JD Review

on:
  workflow_call:
    secrets:
      BOT_ID:
        required: false
        description: "GitHub App ID for the custom bot"
      BOT_KEY:
        required: false
        description: "GitHub App private key for the custom bot"
      CLAUDE_CODE_OAUTH_TOKEN:
        required: true
        description: "Claude Code OAuth token for authentication"
  pull_request:
    types: [opened, ready_for_review]
    #types: [opened, synchronize, ready_for_review, reopened]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

# Permissions set by workflow call
# permissions:
#   contents: read
#   pull-requests: read
#   issues: read
#   id-token: write

jobs:
  setup:
    uses: ./.github/workflows/vars.yml

  jd-review:
    needs: setup
    # Only run if triggered by repository owner or jd-botvin bot
    if: |
      github.event.sender.login == github.repository_owner ||
      github.event.sender.login == 'jd-botvin[bot]'

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Initialize custom bot
        id: bot
        uses: starburst997/custom-bot-init@v1
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Use the repository's CLAUDE.md for guidance on style and conventions. Be constructive and helpful in your feedback.

            Use `gh pr comment` with your Bash tool to leave your review as a comment on the PR.
            DO NOT give a scored review or "stars", no need to "rate" the PR.
            Keep emojis to a minimum.

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: '--allowed-tools "${{ needs.setup.outputs.allowed-tools }}"'

          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ steps.bot.outputs.token }}
          bot_id: ${{ secrets.BOT_ID }}
          bot_name: ${{ steps.bot.outputs.name }}
          allowed_bots: ${{ steps.bot.outputs.slug }}
          plugin_marketplaces: ${{ needs.setup.outputs.plugin-marketplaces }}
          plugins: ${{ needs.setup.outputs.plugins }}
          trigger_phrase: ${{ needs.setup.outputs.trigger-phrase }}
          branch_prefix: ${{ needs.setup.outputs.branch-prefix }}
          assignee_trigger: "@${{ steps.bot.outputs.slug }}"
          label_trigger: ${{ needs.setup.outputs.label-trigger }}
          use_commit_signing: true
